title: A minimalism robotics blog
author: Robotlab Founder, robotlabvn[AT]gmail.com
subtitle: Robotics Lab Blog for everyone

google_analytics:

url:
baseurl:

footer_url:
footer_text: "Copyright © 2023 Robotlab.vn | Contact: robotlabvn@gmail.com"

profile-picture: assets/profile.jpg
favicon_location:

permalink: /:categories/:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "Home"
   link: "https://robotlab.vn"
 - name: "Blog"
   link: "/blog"
 - name: "Tutorial"
   link: "/tutorial"
- name: "Buy me a coffee"
   link: "/buy_coffee"
markdown: kramdown
kramdown:
  math_engine: katex

