title: Xuning Yang
author: Xuning Yang
subtitle: PhD Candidate in Robotics

google_analytics: G-ZEFRYNXSX4

url:
baseurl:

footer_url:
footer_text: "Copyright © 2021 Xuning Yang"

profile-picture: assets/profile.jpg
favicon_location:

permalink: /:categories/:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "cv"
   link: "/Xuning_Yang_CV.pdf"
 - name: "blog"
   link: "/blog"
 - name: "github"
   link: "https://github.com/xuningy"
 - name: "google scholar"
   link: "https://scholar.google.com/citations?hl=en&user=hM9EtNwAAAAJ"

markdown: kramdown
kramdown:
  math_engine: katex
