title: RobotLab.vn
author: Tri Bien 
subtitle: Robotics Blog

google_analytics:

url:
baseurl:

footer_url:
footer_text: "Copyright © 2023 Tri Bien"

profile-picture: assets/profile.jpg
favicon_location:

permalink: /:categories/:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "home"
   link: ""
 - name: "blog"
   link: "/blog"
 - name: "author"
   link: "https://triknight.github.io"
 - name: "github"
   link: "https://github.com/triknight"

markdown: kramdown
kramdown:
  math_engine: katex

