title: A minimalism robotics blog
email: robotlabvn[AT]gmail.com 
subtitle: Robotics Lab Blog for everyone

google_analytics:

url:
baseurl:

footer_url:
footer_text: "Copyright © 2023 Robotlab.vn | Contact: robotlabvn@gmail.com"

profile-picture: assets/profile.jpg
favicon_location:

permalink: /:categories/:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "home"
   link: "https://robotlab.vn"
 - name: "blog"
   link: "/blog"
 - books: "books"
   link: "https://robotlab.vn"

markdown: kramdown
kramdown:
  math_engine: katex

