title: A minimalism robotics blog
author: Robotlab Founder, robotlabvn[AT]gmail.com
subtitle: Robotics Lab Blog for everyone

google_analytics: "G-JZ3ZRCD0LR"

url:
baseurl:

footer_url:
footer_text: "Copyright © 2023 RobotLabX.com | Contact: robotlabvn@gmail.com"

profile-picture: assets/robotlablogo.png
favicon_location:

permalink: /:categories/:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "Home"
   link: "https://robotlabx.com"
 - name: "Blog"
   link: "/blog"
 - name: "Tutorial"
   link: "/tutorial"
markdown: kramdown
kramdown:
  math_engine: katex

