title: A minimalism Robotics blog
author: Tri Bien 
subtitle: Robotics Lab Blog for everyone

google_analytics:

url:
baseurl:

footer_url:
footer_text: "Copyright © 2023 Tri Bien"

profile-picture: assets/profile.jpg
favicon_location:

permalink: /:categories/:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "home"
   link: "https://robotlab.vn"
 - name: "blog"
   link: "/blog"
 - name: "about me"
   link: "https://triknight.github.io"
 - name: "github"
   link: "https://github.com/triknight"

markdown: kramdown
kramdown:
  math_engine: katex

